### PR TITLE
Add support for non-gzipped month archives

### PR DESCRIPTION
**Pull request by miakizz**

### CODE REVIEW

**Comment by kfogel** [comment]
Hey, @nkizz, thanks.  I like the feature, but it would be better to avoid duplicating all that code -- the new block is basically the same as the original gzipped-handling block, except for the subtraction of the "gunzip" line.

A solution would be to wrap the existing block inside a new outer `for` loop, like this:

        for extension in ".txt" ".txt.gz"; do
            for month in (...modify the grep line appropriately...); do
                ...etc...
                ...conditionalize the gunzip line...
            done
        done

That way we have just the single code block, and we map it across the two types of file extension (".txt" and ".txt.gz").

Would you be willing to make that change?

Best regards,
-Karl

**Comment by miakizz** [comment]
I implemented the changes you suggested, thanks for the advice!

**Comment by kfogel** [comment]
Nice, @nkizz!  You've tested with both gzipped and non-gzipped archives?  If so, I'll merge.

**Comment by miakizz** [comment]
Yes, I tested it with both

**Comment by kfogel** [comment]
Merged.  Thank you very much, @nkizz.

**Pull request merged**
